# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2f7e6c07633ab975eba774cd44d3afa3833c4f494f924acbc4c78d1e2337aba475b414ece734e028a6404a5bb064b9f078d803ef5c70766c8911271322f1cca

test:
  secret_key_base: 28ea98fbadc9f499c1168b2c6dcaf8ecc7e45e675bc488f8ed66425cbddc6820975d8b50664e4a7e2634ab8d851b231086ad8cd9efbb975c97ca7d36fd0c5c69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
